services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      - CONNECTIONSTRING=mongodb://db:27017/notes
      - SERVER_PORT=8000
    command: npm start

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
      - db_config:/data/configdb

volumes:
  db:
  db_config:
