name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      - 
        name: prepare node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - 
        name: install dependencies
        run: npm ci
      -  
        name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - 
        name: prepare docker buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: build docker image and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-docker:latest
          
        
          
      
      
